/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminMoreRouteImport } from './routes/admin/more'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminResourceRouteImport } from './routes/admin/$resource'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/classic': typeof ClassicRoute
  '/login': typeof LoginRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/topics': typeof TopicsRoute
  '/writing': typeof WritingRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/classic': typeof ClassicRoute
  '/login': typeof LoginRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/topics': typeof TopicsRoute
  '/writing': typeof WritingRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/classic': typeof ClassicRoute
  '/login': typeof LoginRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/topics': typeof TopicsRoute
  '/writing': typeof WritingRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/classic'
    | '/login'
    | '/podcast'
    | '/topics'
    | '/writing'
    | '/admin/$resource'
    | '/admin/account'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/more'
    | '/admin/reset-password'
    | '/article/$slug'
    | '/book/$slug'
    | '/podcast/$slug'
    | '/topic/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/classic'
    | '/login'
    | '/podcast'
    | '/topics'
    | '/writing'
    | '/admin/$resource'
    | '/admin/account'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/more'
    | '/admin/reset-password'
    | '/article/$slug'
    | '/book/$slug'
    | '/podcast/$slug'
    | '/topic/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/classic'
    | '/login'
    | '/podcast'
    | '/topics'
    | '/writing'
    | '/admin/$resource'
    | '/admin/account'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/more'
    | '/admin/reset-password'
    | '/article/$slug'
    | '/book/$slug'
    | '/podcast/$slug'
    | '/topic/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BooksRoute: typeof BooksRoute
  ClassicRoute: typeof ClassicRoute
  LoginRoute: typeof LoginRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  TopicsRoute: typeof TopicsRoute
  WritingRoute: typeof WritingRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  TopicSlugRoute: typeof TopicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminResourceRoute: typeof AdminResourceRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResourceRoute: AdminResourceRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BooksRoute: BooksRoute,
  ClassicRoute: ClassicRoute,
  LoginRoute: LoginRoute,
  PodcastRoute: PodcastRouteWithChildren,
  TopicsRoute: TopicsRoute,
  WritingRoute: WritingRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  BookSlugRoute: BookSlugRoute,
  TopicSlugRoute: TopicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
